title: Arquillian
description: A container-oriented testing framework for writing real integration tests.
github_organization: arquillian
intense_debate_base_url: http://arquillian.org
intense_debate_acct: xxxxxxxxxxxxxxx
google_analytics: XX-XXXXXXX-X
