title: Arquillian
description: A container-oriented testing framework for writing real integration tests.
github_organization: arquillian
intense_debate_base_url: http://arquillian.org
intense_debate_acct: xxxxxxxxxxxxxxx
google_analytics: XX-XXXXXXX-X
issue_tracker: https://issues.jboss.org/browse/ARQ
ref_guide: https://docs.jboss.org/author/display/ARQ/Home
user_forum: http://community.jboss.org/en/arquillian?view=discussions
dev_forum: http://community.jboss.org/en/arquillian/dev?view=discussions
source_repo: http://github.com/arquillian
